DELIMITER $$

CREATE TRIGGER beforeInsertPhoto
BEFORE INSERT
ON photo
FOR EACH ROW
BEGIN
    SET NEW.createdBy = USER();
    SET NEW.createdAt = CURRENT_DATE();
END$$

CREATE TRIGGER beforeUpdatePhoto
BEFORE UPDATE
ON photo
FOR EACH ROW
BEGIN
    SET NEW.modifiedBy = USER();
    SET NEW.modifiedAt = CURRENT_DATE();
END$$

DELIMITER ;